<a href="https://colab.research.google.com/github/Babonga/Animation-Nation/blob/master/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [10]:
# Import torch
import torch

# Create random tensor
X = torch.rand(size=(7,7))
X, X.shape

(tensor([[7.0226e-04, 3.7274e-01, 9.7872e-01, 9.5645e-01, 8.6886e-01, 1.0236e-01,
          2.8960e-01],
         [3.8936e-01, 2.1878e-01, 4.9368e-01, 3.7895e-01, 8.3285e-01, 8.9016e-01,
          6.0583e-01],
         [3.0146e-01, 3.9479e-01, 7.5070e-01, 8.7906e-01, 3.8748e-01, 5.6183e-01,
          2.9178e-01],
         [9.2232e-02, 1.2844e-01, 4.1231e-01, 8.4270e-01, 4.0418e-01, 8.6211e-02,
          6.1505e-01],
         [2.9713e-01, 9.3522e-01, 5.6323e-01, 9.9627e-01, 8.8735e-01, 8.7080e-01,
          3.1551e-01],
         [8.7267e-01, 8.0206e-01, 7.9775e-01, 4.5872e-01, 1.6965e-01, 5.8399e-01,
          2.1795e-01],
         [9.4364e-01, 9.6337e-01, 5.1320e-01, 3.7242e-02, 1.1567e-01, 3.1235e-01,
          6.6575e-01]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
Y = torch.rand(size=(1,7))
Y, Y.shape
# Perform matrix multiplication
Z =torch.mm(X,Y.T)
Z, Z.shape

(tensor([[1.0556],
         [1.8766],
         [1.2788],
         [0.8505],
         [2.1558],
         [1.5042],
         [1.5872]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7,7))
Y = torch.rand(size=(1,7))

# Matrix multiply tensors
Z = torch.mm(X,Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')
# Create two random tensors on GPU
Tensor_A = torch.rand(size=(2,3)).to(device)
Tensor_B = torch.rand(size=(2,3)).to(device)
Tensor_A, Tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [17]:
# Perform matmul on tensor_A and tensor_B
Z = torch.mm(Tensor_A, Tensor_B.T)
Z, Z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [22]:
# Find max
max = torch.max(Z)
# Find min
min = torch.min(Z)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [23]:
# Find arg max
arg_max = torch.argmax(Z)

# Find arg min
arg_min = torch.argmin(Z)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_C = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_D = tensor_C.squeeze()

# Print out tensors and their shapes
tensor_C, tensor_C.shape, tensor_D, tensor_D.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))